server:
  port: 5597

spring:
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    #url: jdbc:mysql://124.222.89.79:3307/test?serverTimezone=GMT%2B8
    url: jdbc:mysql://124.222.89.79:3307/dev?serverTimezone=GMT%2B8
    password: 1020.hjt
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 4
      timeout: 5000


#
#mybatis-plus:
#  mapper-locations: /mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
